### ISSUE TITLE
Simple image placeholders

### ISSUE THREAD

**Issue by karlpokus** [joereynolds/what-to-code#2]
I found [this](http://placehold.it/350x150).

I like the idea on the needs of charities btw.

**Comment by joereynolds** [comment]
Not exactly. You should be able to say that you want a 3mb file and it'll just produce a file that big. Mainly for testing upload limits on client/server side.

Most placeholder image sites only produce images for a specified size, not a filesize. 
:)

**Comment by karlpokus** [comment]
> Mainly for testing upload limits on client/server side.

Oh. My bad.
