### ISSUE TITLE
Tagpro does not send all player location data to each player.

### ISSUE THREAD

**Issue by christopherjenness** [joereynolds/what-to-code#3]
"A tagpro add-on that shows the entire map and the location of all the players"

Tagpro does not send all player location data to players  It only sends player location data of players near you.  This would be impossible to create.

**Comment by joereynolds** [comment]
There's a `tagpro.players` array that contains each player object.

Try it out, enter this in the console in game

`tagpro.players[1].x`
`tagpro.players[1].y`

They have that for every ball, so it should be possible to map it to a grid

**Comment by christopherjenness** [comment]
As far as I can tell, this does not work on production servers.  Only tangent.

**Comment by Nick-Riggs** [comment]
No, the server does not send a player the positions of other players, if outside the default field of view.

**Comment by christopherjenness** [comment]
https://www.reddit.com/r/TagPro/comments/4x9p7a/does_tagpro_send_you_data_on_all_player_locations/d6dn91u

The creator claims you are not correct.

**Comment by joereynolds** [comment]
Interesting, I left a comment
