### ISSUE TITLE
Markdown: No-op?

### ISSUE THREAD

**Issue by BenWiederhake** [joereynolds/what-to-code#4]
Regarding the following entry:

> A site generator based on markdown files and no setup. You send the file over to the server and it renders it for you, that's it!

Hmm.  Sounds exactly like what `markdown` already does.  Give it a markdown file, it outputs HTML.  Tell your HTTP server to serve that file -- or open it in your browser directly.  Just reload the tab by hand when editing the file.

So, what exactly do you need there?

**Comment by joereynolds** [comment]
Is `markdown` a package or are you referring to the format?
A browser won't just render a `.md` file for you if that's what you mean?

**Comment by BenWiederhake** [comment]
I mean the [original implementation of Markdown](https://daringfireball.net/projects/markdown/), which was "just" a simple tool that took a Markdown file and produced a HTML file (or wrote it to stdout).

This original markdown implementation (which is/was is perl) is available in [Debian](https://packages.debian.org/jessie/markdown)

There also seems to be a [C implementation called `discount`](http://www.pell.portland.or.us/~orc/Code/discount/), a [Python implementation](https://github.com/waylan/Python-Markdown) (that even properly acknowledges who came first and that it's compatible with the original Markdown flavor), and of course a [NodeJS implementation](https://github.com/evilstreak/markdown-js).

There's even a list that claims to be all the differences between [GFM and actual Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), but (sadly) no list of things that Github automatically filters and removes before serving it.

Apart from that, there's lots of plugins for Eclipse, IntelliJ, and dedicated IDEs, that allow you to write Markdown with preview, side-by-side.

Does that fit your needs?

**Comment by joereynolds** [comment]
Ah yeah, that's pretty much exactly what I meant!
Sorry for the confusion D:
